# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-04 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeededSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
            options={
                'verbose_name': 'Needed skill',
                'verbose_name_plural': 'Needed skills',
            },
        ),
        migrations.AlterModelOptions(
            name='profileskill',
            options={'verbose_name': 'Profile skill', 'verbose_name_plural': 'Profile skills'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AddField(
            model_name='neededskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Skill'),
        ),
    ]
